#pragma once

//------------------------------------
// Generated by ArduinoCodeGen.
// Manual modifications will be LOST!
//                                 Bn
//------------------------------------

const char *serverCert = "-----BEGIN CERTIFICATE-----\n" \
"MIIDzTCCArWgAwIBAgIUaPMGKFM7X5lI4gEIw6sRoc/rc3wwDQYJKoZIhvcNAQEL\n" \
"BQAwdjELMAkGA1UEBhMCTFYxDTALBgNVBAcMBFJpZ2ExGTAXBgNVBAoMEEJuIEVu\n" \
"dGVydGFpbm1lbnQxPTA7BgNVBAMMNGVjMi02My0xNzYtMjEwLTMxLmV1LWNlbnRy\n" \
"YWwtMS5jb21wdXRlLmFtYXpvbmF3cy5jb20wHhcNMjUwNTAzMTYxNTQ2WhcNMjYw\n" \
"NTAzMTYxNTQ2WjB2MQswCQYDVQQGEwJMVjENMAsGA1UEBwwEUmlnYTEZMBcGA1UE\n" \
"CgwQQm4gRW50ZXJ0YWlubWVudDE9MDsGA1UEAww0ZWMyLTYzLTE3Ni0yMTAtMzEu\n" \
"ZXUtY2VudHJhbC0xLmNvbXB1dGUuYW1hem9uYXdzLmNvbTCCASIwDQYJKoZIhvcN\n" \
"AQEBBQADggEPADCCAQoCggEBAI+OI+bsVde0N/SyUmO7E81nxGNsaakNIEaWoWnC\n" \
"rlmrmFt6xd+yBLHyqFcUu9XqyAPMa0igR7FBcxQBNJIeTE6R/TFJJi+PbpSp62bs\n" \
"fq5AimGnqLT50pOLDZrRZdyUBP8+2oeCdNjGecYGEB3SYoO6xqBfwEIZGmFta8EK\n" \
"u44/+ryrmf1Asut8/yxy1boPHK3ctat3gS5aSrDJQM52Az4CZKGAiRemoC1GUaij\n" \
"xwbmNjRsKogdc+9CAO3gqbkRnv90qPUl6niSFBNspcEO4x+InvNsghJlo37BpDSK\n" \
"nPbw1Z1atxiLzASb44OIPnXrcbM/DbT0PbDugFZYv3Zk8UcCAwEAAaNTMFEwHQYD\n" \
"VR0OBBYEFKu0xGyJF5+8PgVN/NkJ0piQr4XpMB8GA1UdIwQYMBaAFKu0xGyJF5+8\n" \
"PgVN/NkJ0piQr4XpMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\n" \
"AFpg7mbW8TS/doSgmJfXCkLqbhk1VBwPFWhAe9UegytXG3d8ASTbB1Jw9bc/ilTc\n" \
"+6OEMi7GhvibZoOC10W29/x5OnDW8q1uTLN+ErnQeY4Jhh99z8Jik+0YQ0gTezvT\n" \
"GasZ5aJHZvhFncLaVDLdHnv1aoLAtbVgxrtXtd7t8zuh3BTRGA9qlJAzqIvGaexV\n" \
"OLHRVN9ysRWINOvjXVziVt5RaItDS+Sj6Nt+HrQqg23qSoMCCN0mpohP74uy0FiU\n" \
"6iI+2Rpck7Y8qu9FELivuFYt+pFjbQhRFsPcj4kHc/eao2NR+4SVN1ZeiaXPNcc5\n" \
"MaAH1LXfJMgHGkwiDhqQgTY=\n" \
"-----END CERTIFICATE-----";