#pragma once

//------------------------------------
// Generated by ArduinoCodeGen.
// Manual modifications will be LOST!
//                                 Bn
//------------------------------------

const char *serverCert = "-----BEGIN CERTIFICATE-----\n" \
"MIIDyTCCArGgAwIBAgIUE+J27dp0IMAtBnaaDfWO7y+5N7owDQYJKoZIhvcNAQEL\n" \
"BQAwdDELMAkGA1UEBhMCTFYxDTALBgNVBAcMBFJpZ2ExGTAXBgNVBAoMEEJuIEVu\n" \
"dGVydGFpbm1lbnQxOzA5BgNVBAMMMmVjMi0zLTc4LTcwLTE2OC5ldS1jZW50cmFs\n" \
"LTEuY29tcHV0ZS5hbWF6b25hd3MuY29tMB4XDTI0MDYxOTE4NDMzMVoXDTI1MDYx\n" \
"OTE4NDMzMVowdDELMAkGA1UEBhMCTFYxDTALBgNVBAcMBFJpZ2ExGTAXBgNVBAoM\n" \
"EEJuIEVudGVydGFpbm1lbnQxOzA5BgNVBAMMMmVjMi0zLTc4LTcwLTE2OC5ldS1j\n" \
"ZW50cmFsLTEuY29tcHV0ZS5hbWF6b25hd3MuY29tMIIBIjANBgkqhkiG9w0BAQEF\n" \
"AAOCAQ8AMIIBCgKCAQEAnffvSTNk8j6zz7snrshdGNrmftNmeo1QU8e/meA+Adt1\n" \
"yhhuIW1OR3mllwFAsdCDiNzppO9LkokOvbBgxIZrTjjs0oitgIxEboMJWAxg2yAo\n" \
"Idzl79SoCO1a/aesh7szfbnJmo0xl7u7QlhItzCUQ5T6hV185S42RatZgMuKG6m/\n" \
"x6VNxCKjl8KAXUHhQBynco885IqZ7a4olv6gCVtwEOpfyzae7uy5LZt9908kwaQX\n" \
"rRBp5LhwqBuTirL/JY/vfZhTMlXPKofkT+FRNBhu0qzUrLAaRVKcTkm4x3eioyv+\n" \
"UHQiuzcr1CQY3wV6zxdHRyqsnk4tpJXRhtJH1P3OiwIDAQABo1MwUTAdBgNVHQ4E\n" \
"FgQUVz9+PD+nzqcGn8HRYSdUaWQ619owHwYDVR0jBBgwFoAUVz9+PD+nzqcGn8HR\n" \
"YSdUaWQ619owDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEANmMg\n" \
"t9s1AF2rDe2mClFgnqoVDZDxTYQ3wLdUJZlMu45WKm++kTc51VpXryydw4yw+p61\n" \
"1VYIox71zcoKrk6YVfXz55Z1xidRj6WGyMFJBlXoCcORjoKD3ok7lBdpe5CrF6vr\n" \
"RHwjKNqTynY/oTUZtEcRyI/F4rxMHZnS2SMm6M/w0fczCD1v2o/id5XGW0VzDpQW\n" \
"AjyiIXMsuwF4MO+gkYIl6z/xKy15EDPUWymZbUoK8rNjeMzemfKfKEfsDIKGcR3f\n" \
"+VxZyWlPzft2yTwxMLgdAdVTsmGNALMJPxkTCS3I3OwUs2NveWDIDLjn1OqZLoCL\n" \
"hiOVpBu7oBALwsD54w==\n" \
"-----END CERTIFICATE-----";